### ISSUE TITLE
Screenshots please!

### ISSUE THREAD

**Issue by luzpaz** [wfpaisa/Plane-freecad#1]
Do you mind adding screenshots to the README ?

**Comment by luzpaz** [comment]
@wfpaisa bump

**Comment by luzpaz** [comment]
CC @pgilfernandez  
JFYI

**Comment by luzpaz** [comment]
bump

**Comment by wfpaisa** [comment]
Sorry Luzpaz, in this momen I'm exploring icon color concepts, I want to black/white but the disable colors doesn't look good, I update the README.md already you can see a BETA preview.

**Comment by luzpaz** [comment]
Have you looked at https://github.com/formjune/1D_SVG_Tools ?
Also if you're gonna mess with the icons, please consider these guidelines: https://forum.freecadweb.org/viewtopic.php?f=34&t=19952#p153819

Edit: thanks for adding the screenshot, looks great so far
